name: automated_script_runner

on:  
  schedule:
          - cron: '59 10 * * *'
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.Website_Updater }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # install setup.py
        pip install .
        pip install pycodestyle
        pip install pylint
        pip install argparse
        pip install matplotlib
        pip install pandas
        pip install pandas-bokeh
    - name: Run Covid19_graphs
      run: |
        covid19_graphs ./
    - name: Commiter
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          'Updates to Graphics'
          skip-checks: true
      run: |
          git config --global user.name 'DLBPointon'
          git config --global user.email 'damonlbp@hotmail.co.uk'
          git commit -am "Updates for today"
          git push
