name: automated_script_runner

on:  
  schedule:
          - cron: '59 10 * * *'
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # install setup.py
        pip install .
        pip install pycodestyle
        pip install pylint
        pip install argparse
        pip install matplotlib
        pip install pandas
        pip install pandas-bokeh
    - name: Run Covid19_graphs
      run: |
        covid19_graphs ./
    - name: Commit files
      run: |
        git config --local user.email "damonlbp@hotmail.co.uk"
        git config --local user.name "DLBPointon"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
